<!DOCTYPE html>
<html>

<head>
    <title>EKGViewer - Definitions</title>
    <link href="./css/reset.css" rel="stylesheet" />
    <link href="./templates/css/page-template.css" rel="stylesheet" />
    <link href="./css/definitions.css" rel="stylesheet" />
</head>

<body>
    <?php include "./templates/page-header.php" ?>
    <section id="content-wrapper">
        <h1>Definitions</h1>
        <section class="definitions">
            <div>
                <ul>
                    <li><b>Electrocardiograms</b> - record of the electrical signals in your heart, also called ECGs or EKGs. A simple EKG can be seen with three electrodes known as lead I, lead II, and lead III.</li>
                    <li><b>Lead</b> - a view of the heart from a particular angle.</li>
                    <li><b>Lead I Monitoring</b> - positive electrode is placed on the left upper apex of the chest, just below the clavicle; the negative electrode is placed below the right clavicle. Lead I accesses information on the lateral wall of the heart.</li>
                    <li><b>Lead II Monitoring</b> - The positive electrode is placed on the left side of the chest below the pectoral muscle; the negative electrode is placed below the right clavicle. Lead II access information on the inferior wall of the heart.</li>
                    <li><b>Lead III Monitoring</b> - The positive electrode is placed on the left side of the chest below the pectoral muscle; the negative electrode is placed on the left side also but below the clavicle. Lead III accesses information on the inferior wall of the heart.</li>
                    <li><b>Lead MCL1 Monitoring</b> - The negative electrode is on the left side of the chest below the clavicle; the positive electrode is on the right side of the sternum in the 4th intercostal space. Lead MCL1 accesses information on the anterior wall of the heart.</li>
                    <li><b>Cardiac cells</b> - cells that make up the heart/cardiac muscles. Two basic types of cardiac cells include: myocardial and specialized cells.</li>
                    <li><b>Myocardial cells</b> - working machinery of the heart, compose the majority of heart tissue. Form the muscular layer of the atrial and ventricular walls.</li>
                    <li><b>Specialized cells</b> - the conduction system of the heart.</li>
                    <li><b>Pacemaker cells</b> - activate and regulate myocardial cells.</li>
                    <li><b>Electrical conducting cells</b> - conduct impulses generated by pacemaker cells through the heart.</li>
                    <li><b>P wave</b> - the wave formed by the cardiac cycle beginning with SA node sending an impulse that depolarizes the right and left atria.</li>
                    <li><b>PR segment</b> - flat and represents a delay, very little electrical activity.</li>
                    <li><b>PR interval</b> - P wave plus the PR segment.</li>
                    <li><b>QRS complex</b> - produced by the ventricular depolarization, made up by the Q wave, the R wave, and the S wave.</li>
                    <li><b>ST segment</b> - the beginning of repolarization of the ventricles.</li>
                    <li><b>T wave</b> - follows the ST segment and represents repolarization of the ventricles.</li>
                    <li><b>QT interval</b> - from the beginning of the QRS complex to the end of the T wave; the QT interval is the depolarization and repolarization of the ventricles.</li>
                    <li><b>U wave</b> - believed to be the repolarization of the Purkinje fibers a U wave will follow a T wave and go in the same direction.</li>
                </ul>
            </div>
        </section>
    </section>
    <?php include "./templates/page-footer.php" ?>
</body>

</html>
